name: Update README with recent repositories

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Recent Repositories
        run: |
          curl -s https://api.github.com/users/shakil-md-abdullahal/repos?sort=created&per_page=3 | \
          jq -r '.[] | "* [\(.name)](\(.html_url))"' > recent-repos.md

      - name: Update README file
        run: |
          sed -i '/<!--RECENT_REPOS_START-->/,/<!--RECENT_REPOS_END-->/{/<!--RECENT_REPOS_START-->/!{/<!--RECENT_REPOS_END-->/!d}}' README.md
          sed -i '/<!--RECENT_REPOS_START-->/r recent-repos.md' README.md

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update recent repositories" || echo "No changes to commit"
          git push
